[2022-03-20 15:04:28,431] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.dowload_desc 2022-03-19T00:00:00+00:00 [queued]>
[2022-03-20 15:04:28,442] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.dowload_desc 2022-03-19T00:00:00+00:00 [queued]>
[2022-03-20 15:04:28,442] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 15:04:28,442] {taskinstance.py:1043} INFO - Starting attempt 3 of 3
[2022-03-20 15:04:28,443] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 15:04:28,456] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): dowload_desc> on 2022-03-19T00:00:00+00:00
[2022-03-20 15:04:28,459] {standard_task_runner.py:52} INFO - Started process 81 to run task
[2022-03-20 15:04:28,462] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_news', 'dowload_desc', '2022-03-19T00:00:00+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_news.py', '--cfg-path', '/tmp/tmpb7avx8kw', '--error-file', '/tmp/tmptzvkahzp']
[2022-03-20 15:04:28,463] {standard_task_runner.py:77} INFO - Job 24: Subtask dowload_desc
[2022-03-20 15:04:28,505] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_news.dowload_desc 2022-03-19T00:00:00+00:00 [running]> on host 0b08bfee94e8
[2022-03-20 15:04:28,551] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_news
AIRFLOW_CTX_TASK_ID=dowload_desc
AIRFLOW_CTX_EXECUTION_DATE=2022-03-19T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-19T00:00:00+00:00
[2022-03-20 15:04:28,551] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-20 15:04:28,552] {bash.py:158} INFO - Running command: curl -o news_nvidia_2022-03-19_2022-03-20.jsonhttps://newsapi.org/v2/everything -G-d from=2022-03-19-d to=2022-03-20-d language=en-d q=nvidia-d apiKey=1ddd1951b81c4e9eb662cc118c33ff6a
[2022-03-20 15:04:28,558] {bash.py:169} INFO - Output:
[2022-03-20 15:04:28,565] {bash.py:173} INFO - curl: option -G-d: is unknown
[2022-03-20 15:04:28,565] {bash.py:173} INFO - curl: try 'curl --help' or 'curl --manual' for more information
[2022-03-20 15:04:28,566] {bash.py:177} INFO - Command exited with return code 2
[2022-03-20 15:04:28,577] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-20 15:04:28,579] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_news, task_id=dowload_desc, execution_date=20220319T000000, start_date=20220320T150428, end_date=20220320T150428
[2022-03-20 15:04:28,636] {local_task_job.py:146} INFO - Task exited with return code 1
