[2022-03-20 21:35:50,205] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.dowload_desc 2022-03-15T00:00:00+00:00 [queued]>
[2022-03-20 21:35:50,222] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: fetch_news.dowload_desc 2022-03-15T00:00:00+00:00 [queued]>
[2022-03-20 21:35:50,222] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 21:35:50,222] {taskinstance.py:1043} INFO - Starting attempt 10 of 10
[2022-03-20 21:35:50,222] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 21:35:50,240] {taskinstance.py:1063} INFO - Executing <Task(BashOperator): dowload_desc> on 2022-03-15T00:00:00+00:00
[2022-03-20 21:35:50,252] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_news', 'dowload_desc', '2022-03-15T00:00:00+00:00', '--job-id', '501', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_news.py', '--cfg-path', '/tmp/tmpo4x2oi9b', '--error-file', '/tmp/tmpkw5tvfb6']
[2022-03-20 21:35:50,252] {standard_task_runner.py:77} INFO - Job 501: Subtask dowload_desc
[2022-03-20 21:35:50,244] {standard_task_runner.py:52} INFO - Started process 1132 to run task
[2022-03-20 21:35:50,379] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_news.dowload_desc 2022-03-15T00:00:00+00:00 [running]> on host e39215f0be5b
[2022-03-20 21:35:50,441] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_news
AIRFLOW_CTX_TASK_ID=dowload_desc
AIRFLOW_CTX_EXECUTION_DATE=2022-03-15T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-15T00:00:00+00:00
[2022-03-20 21:35:50,442] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2022-03-20 21:35:50,442] {bash.py:158} INFO - Running command: curl -o /tmp_2022-03-15_2022-03-16/news_nvidia.json https://newsapi.org/v2/everything -G -d from=2022-03-15 -d to=2022-03-16 -d language=en -d q=nvidia -d apiKey=1ddd1951b81c4e9eb662cc118c33ff6a
[2022-03-20 21:35:50,453] {bash.py:169} INFO - Output:
[2022-03-20 21:35:50,461] {bash.py:173} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2022-03-20 21:35:50,461] {bash.py:173} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2022-03-20 21:35:50,682] {bash.py:173} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file
[2022-03-20 21:35:50,682] {bash.py:173} INFO - Warning: /tmp_2022-03-15_2022-03-16/news_nvidia.json: No such file or
[2022-03-20 21:35:50,682] {bash.py:173} INFO - Warning: directory
[2022-03-20 21:35:50,682] {bash.py:173} INFO - 100   259  100   259    0     0   1171      0 --:--:-- --:--:-- --:--:--  1177
[2022-03-20 21:35:50,682] {bash.py:173} INFO - curl: (23) Failed writing body (0 != 259)
[2022-03-20 21:35:50,683] {bash.py:177} INFO - Command exited with return code 23
[2022-03-20 21:35:50,697] {taskinstance.py:1455} ERROR - Bash command failed. The command returned a non-zero exit code.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2022-03-20 21:35:50,699] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=fetch_news, task_id=dowload_desc, execution_date=20220315T000000, start_date=20220320T213550, end_date=20220320T213550
[2022-03-20 21:35:50,750] {local_task_job.py:146} INFO - Task exited with return code 1
