[2022-03-21 18:40:32,412] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_postgress.python_task 2022-03-21T18:40:09.132037+00:00 [None]>
[2022-03-21 18:40:32,427] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_postgress.python_task 2022-03-21T18:40:09.132037+00:00 [None]>
[2022-03-21 18:40:32,428] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 18:40:32,428] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-03-21 18:40:32,428] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-03-21 18:40:32,437] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): python_task> on 2022-03-21T18:40:09.132037+00:00
[2022-03-21 18:40:32,441] {standard_task_runner.py:52} INFO - Started process 396 to run task
[2022-03-21 18:40:32,444] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test_postgress', 'python_task', '2022-03-21T18:40:09.132037+00:00', '--job-id', '775', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/test_postgress.py', '--cfg-path', '/tmp/tmpvchdk172', '--error-file', '/tmp/tmp9b_85aps']
[2022-03-21 18:40:32,445] {standard_task_runner.py:77} INFO - Job 775: Subtask python_task
[2022-03-21 18:40:32,484] {logging_mixin.py:104} INFO - Running <TaskInstance: test_postgress.python_task 2022-03-21T18:40:09.132037+00:00 [running]> on host dd6a275532f2
[2022-03-21 18:40:32,563] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_postgress
AIRFLOW_CTX_TASK_ID=python_task
AIRFLOW_CTX_EXECUTION_DATE=2022-03-21T18:40:09.132037+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-21T18:40:09.132037+00:00
[2022-03-21 18:40:33,514] {base.py:74} INFO - Using connection to: id: news_in. Host: postgres, Port: 5432, Schema: , Login: airflow, Password: XXXXXXXX, extra: None
[2022-03-21 18:40:33,543] {logging_mixin.py:104} INFO -     query
0  nvidia
1   apple
[2022-03-21 18:40:33,543] {python.py:118} INFO - Done. Returned value was: None
[2022-03-21 18:40:33,582] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=test_postgress, task_id=python_task, execution_date=20220321T184009, start_date=20220321T184032, end_date=20220321T184033
[2022-03-21 18:40:33,630] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-03-21 18:40:33,671] {local_task_job.py:146} INFO - Task exited with return code 0
