[2022-03-21 09:53:58,398] {taskinstance.py:845} INFO - Dependencies not met for <TaskInstance: test_postgress.create_pet_table 2022-03-01T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state which is not a valid state for execution. The task must be cleared in order to be run.
[2022-03-21 09:53:58,404] {local_task_job.py:93} INFO - Task is not able to be run
